.PHONY: clean All

All:
	@echo "----------Building project:[ ArraysPractice - Debug ]----------"
	@cd "ArraysPractice" && "$(MAKE)" -f  "ArraysPractice.mk"
clean:
	@echo "----------Cleaning project:[ ArraysPractice - Debug ]----------"
	@cd "ArraysPractice" && "$(MAKE)" -f  "ArraysPractice.mk" clean
