.PHONY: clean All

All:
	@echo "----------Building project:[ MyStringReversal - Debug ]----------"
	@cd "MyStringReversal" && "$(MAKE)" -f  "MyStringReversal.mk"
clean:
	@echo "----------Cleaning project:[ MyStringReversal - Debug ]----------"
	@cd "MyStringReversal" && "$(MAKE)" -f  "MyStringReversal.mk" clean
