.PHONY: clean All

All:
	@echo "----------Building project:[ GradesMy - Debug ]----------"
	@cd "GradesMy" && "$(MAKE)" -f  "GradesMy.mk"
clean:
	@echo "----------Cleaning project:[ GradesMy - Debug ]----------"
	@cd "GradesMy" && "$(MAKE)" -f  "GradesMy.mk" clean
