.PHONY: clean All

All:
	@echo "----------Building project:[ Billion_count_my - Debug ]----------"
	@cd "Billion_count_my" && "$(MAKE)" -f  "Billion_count_my.mk"
clean:
	@echo "----------Cleaning project:[ Billion_count_my - Debug ]----------"
	@cd "Billion_count_my" && "$(MAKE)" -f  "Billion_count_my.mk" clean
