.PHONY: clean All

All:
	@echo "----------Building project:[ SuperChallengeMy - Debug ]----------"
	@cd "SuperChallengeMy" && "$(MAKE)" -f  "SuperChallengeMy.mk"
clean:
	@echo "----------Cleaning project:[ SuperChallengeMy - Debug ]----------"
	@cd "SuperChallengeMy" && "$(MAKE)" -f  "SuperChallengeMy.mk" clean
